### ISSUE TITLE
Add documentation following standard Rust documentation style

### ISSUE THREAD

**Issue by eywalker** [walkerlab/orcapod#24] opened 2024-10-13 15:38 UTC
We should provide documentation on our module as we go and follow standard Rust documentation practices. 
* https://doc.rust-lang.org/rust-by-example/meta/doc.html
* https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html

**Comment by guzman-raphael** [comment] 2024-10-14 00:17
Duplicate of #20

**Closed as completed by guzman-raphael** 2024-10-14 00:17 UTC
Labels: documentation, duplicate
